name: Bug report
description: Report a reproducible bug
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report. Please include enough detail for maintainers to reproduce.

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide a numbered list of steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Node version, pnpm version, browser (if UI)

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or attach screenshots where relevant.
