/**
 * CMS Blueprint Seed Data for freeblackmarket.com
 * Complete taxonomy structure: Types → Categories → Tags → Attributes
 */

// ============================================================================
// TYPES - Top-level product/service classifications
// ============================================================================
export const CMS_TYPES = [
  {
    id: "type_food_produce",
    handle: "food-produce",
    name: "Food & Produce",
    description: "Fresh fruits, vegetables, grains, meat, dairy, and beverages from local farms and producers",
    icon: "🥬",
    display_order: 1,
    is_active: true,
  },
  {
    id: "type_prepared_foods",
    handle: "prepared-foods-meals",
    name: "Prepared Foods & Meals",
    description: "Ready-to-eat breakfast, lunch, dinner, snacks, desserts, and beverages",
    icon: "🍽️",
    display_order: 2,
    is_active: true,
  },
  {
    id: "type_supplies_goods",
    handle: "supplies-goods",
    name: "Supplies & Goods",
    description: "Household items, personal care, cleaning supplies, and pantry staples",
    icon: "📦",
    display_order: 3,
    is_active: true,
  },
  {
    id: "type_services_delivery",
    handle: "services-delivery",
    name: "Services & Delivery",
    description: "Local delivery, catering, meal prep, transport, and logistics services",
    icon: "🚚",
    display_order: 4,
    is_active: true,
  },
  {
    id: "type_organizations",
    handle: "organizations-partnerships",
    name: "Organizations & Partnerships",
    description: "Food banks, mutual aid groups, community programs, gardens, and commercial kitchens",
    icon: "🤝",
    display_order: 5,
    is_active: true,
  },
  {
    id: "type_equipment_tools",
    handle: "equipment-tools",
    name: "Equipment & Tools",
    description: "Kitchen equipment, gardening tools, and small machinery",
    icon: "🔧",
    display_order: 6,
    is_active: true,
  },
]

// ============================================================================
// CATEGORIES - Second-level classifications under each Type
// ============================================================================
export const CMS_CATEGORIES = [
  // --- Food & Produce Categories ---
  {
    id: "cat_fruits",
    type_id: "type_food_produce",
    handle: "fruits",
    name: "Fruits",
    description: "Fresh, frozen, and canned fruits from local farms",
    icon: "🍎",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat_vegetables",
    type_id: "type_food_produce",
    handle: "vegetables",
    name: "Vegetables",
    description: "Fresh, frozen, and canned vegetables from local farms",
    icon: "🥕",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat_grains_legumes",
    type_id: "type_food_produce",
    handle: "grains-legumes",
    name: "Grains & Legumes",
    description: "Rice, beans, lentils, quinoa, and other grains",
    icon: "🌾",
    display_order: 3,
    is_active: true,
  },
  {
    id: "cat_meat_seafood",
    type_id: "type_food_produce",
    handle: "meat-seafood",
    name: "Meat & Seafood",
    description: "Fresh and frozen meat, poultry, and seafood",
    icon: "🥩",
    display_order: 4,
    is_active: true,
  },
  {
    id: "cat_dairy_eggs",
    type_id: "type_food_produce",
    handle: "dairy-eggs",
    name: "Dairy & Eggs",
    description: "Milk, cheese, yogurt, eggs, and dairy alternatives",
    icon: "🥛",
    display_order: 5,
    is_active: true,
  },
  {
    id: "cat_beverages_produce",
    type_id: "type_food_produce",
    handle: "beverages-produce",
    name: "Beverages",
    description: "Fresh juices, farm beverages, and artisan drinks",
    icon: "🧃",
    display_order: 6,
    is_active: true,
  },

  // --- Prepared Foods & Meals Categories ---
  {
    id: "cat_breakfast",
    type_id: "type_prepared_foods",
    handle: "breakfast",
    name: "Breakfast",
    description: "Ready-to-eat breakfast items and morning meals",
    icon: "🍳",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat_lunch_dinner",
    type_id: "type_prepared_foods",
    handle: "lunch-dinner",
    name: "Lunch & Dinner",
    description: "Prepared lunch and dinner entrees",
    icon: "🍲",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat_snacks",
    type_id: "type_prepared_foods",
    handle: "snacks",
    name: "Snacks",
    description: "Prepared snacks and light bites",
    icon: "🥨",
    display_order: 3,
    is_active: true,
  },
  {
    id: "cat_desserts",
    type_id: "type_prepared_foods",
    handle: "desserts",
    name: "Desserts",
    description: "Sweet treats, pastries, and dessert items",
    icon: "🍰",
    display_order: 4,
    is_active: true,
  },
  {
    id: "cat_beverages_prepared",
    type_id: "type_prepared_foods",
    handle: "beverages-prepared",
    name: "Beverages",
    description: "Prepared drinks, smoothies, and specialty beverages",
    icon: "🥤",
    display_order: 5,
    is_active: true,
  },

  // --- Supplies & Goods Categories ---
  {
    id: "cat_household_items",
    type_id: "type_supplies_goods",
    handle: "household-items",
    name: "Household Items",
    description: "Home essentials and household products",
    icon: "🏠",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat_personal_care",
    type_id: "type_supplies_goods",
    handle: "personal-care",
    name: "Personal Care",
    description: "Personal hygiene and care products",
    icon: "🧴",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat_cleaning_supplies",
    type_id: "type_supplies_goods",
    handle: "cleaning-supplies",
    name: "Cleaning Supplies",
    description: "Cleaning products and supplies",
    icon: "🧹",
    display_order: 3,
    is_active: true,
  },
  {
    id: "cat_pantry_staples",
    type_id: "type_supplies_goods",
    handle: "pantry-staples",
    name: "Pantry Staples",
    description: "Essential pantry items and dry goods",
    icon: "🫙",
    display_order: 4,
    is_active: true,
  },

  // --- Services & Delivery Categories ---
  {
    id: "cat_local_delivery",
    type_id: "type_services_delivery",
    handle: "local-delivery",
    name: "Local Delivery",
    description: "Local delivery services for food and goods",
    icon: "🚗",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat_catering_meal_prep",
    type_id: "type_services_delivery",
    handle: "catering-meal-prep",
    name: "Catering & Meal Prep",
    description: "Catering services and meal preparation",
    icon: "👨‍🍳",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat_transport_logistics",
    type_id: "type_services_delivery",
    handle: "transport-logistics",
    name: "Transport & Logistics",
    description: "Transport and logistics services",
    icon: "📦",
    display_order: 3,
    is_active: true,
  },

  // --- Organizations & Partnerships Categories ---
  {
    id: "cat_food_banks",
    type_id: "type_organizations",
    handle: "food-banks",
    name: "Food Banks",
    description: "Local food banks and food distribution centers",
    icon: "🏪",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat_mutual_aid",
    type_id: "type_organizations",
    handle: "mutual-aid-groups",
    name: "Mutual Aid Groups",
    description: "Community mutual aid organizations",
    icon: "🤲",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat_community_programs",
    type_id: "type_organizations",
    handle: "community-programs",
    name: "Community Programs",
    description: "Community education and support programs",
    icon: "📚",
    display_order: 3,
    is_active: true,
  },
  {
    id: "cat_community_gardens",
    type_id: "type_organizations",
    handle: "community-gardens",
    name: "Community Gardens",
    description: "Urban farms and community garden spaces",
    icon: "🌱",
    display_order: 4,
    is_active: true,
  },
  {
    id: "cat_community_kitchens",
    type_id: "type_organizations",
    handle: "community-commercial-kitchens",
    name: "Community Commercial Kitchens",
    description: "Shared commercial kitchen facilities",
    icon: "🍳",
    display_order: 5,
    is_active: true,
  },

  // --- Equipment & Tools Categories ---
  {
    id: "cat_kitchen_equipment",
    type_id: "type_equipment_tools",
    handle: "kitchen-equipment",
    name: "Kitchen Equipment",
    description: "Commercial and home kitchen equipment",
    icon: "🔪",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat_gardening_tools",
    type_id: "type_equipment_tools",
    handle: "gardening-tools",
    name: "Gardening Tools",
    description: "Garden and farming tools",
    icon: "🌿",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat_small_machinery",
    type_id: "type_equipment_tools",
    handle: "small-machinery",
    name: "Small Machinery",
    description: "Small equipment and machinery",
    icon: "⚙️",
    display_order: 3,
    is_active: true,
  },
]

// ============================================================================
// TAGS - Labels/filters for products and services
// ============================================================================
export const CMS_TAGS = [
  // --- Dietary Tags ---
  { id: "tag_organic", handle: "organic", name: "Organic", tag_type: "dietary", color: "#22c55e" },
  { id: "tag_vegan", handle: "vegan", name: "Vegan", tag_type: "dietary", color: "#16a34a" },
  { id: "tag_gluten_free", handle: "gluten-free", name: "Gluten-Free", tag_type: "dietary", color: "#eab308" },
  { id: "tag_keto", handle: "keto", name: "Keto", tag_type: "dietary", color: "#f97316" },
  { id: "tag_low_sugar", handle: "low-sugar", name: "Low-Sugar", tag_type: "dietary", color: "#06b6d4" },

  // --- Availability Tags ---
  { id: "tag_in_stock", handle: "in-stock", name: "In-stock", tag_type: "availability", color: "#22c55e" },
  { id: "tag_pre_order", handle: "pre-order", name: "Pre-order", tag_type: "availability", color: "#3b82f6" },
  { id: "tag_seasonal", handle: "seasonal", name: "Seasonal", tag_type: "availability", color: "#f59e0b" },
  { id: "tag_ready_to_eat", handle: "ready-to-eat", name: "Ready-to-eat", tag_type: "availability", color: "#10b981" },

  // --- Source Tags ---
  { id: "tag_farm", handle: "farm", name: "Farm", tag_type: "source", color: "#84cc16" },
  { id: "tag_artisan", handle: "artisan", name: "Artisan", tag_type: "source", color: "#a855f7" },
  { id: "tag_nonprofit", handle: "nonprofit", name: "Nonprofit", tag_type: "source", color: "#ec4899" },
  { id: "tag_maker", handle: "maker", name: "Maker", tag_type: "source", color: "#8b5cf6" },
  { id: "tag_locally_made", handle: "locally-made", name: "Locally-made", tag_type: "source", color: "#14b8a6" },
  { id: "tag_artisanal", handle: "artisanal", name: "Artisanal", tag_type: "source", color: "#d946ef" },

  // --- Fulfillment Tags ---
  { id: "tag_delivery", handle: "delivery", name: "Delivery", tag_type: "fulfillment", color: "#3b82f6" },
  { id: "tag_pickup", handle: "pickup", name: "Pickup", tag_type: "fulfillment", color: "#6366f1" },
  { id: "tag_local_only", handle: "local-only", name: "Local Only", tag_type: "fulfillment", color: "#0ea5e9" },

  // --- Pricing Tags ---
  { id: "tag_bulk_sale", handle: "bulk-sale", name: "Bulk Sale", tag_type: "pricing", color: "#f97316" },
  { id: "tag_fair_trade", handle: "fair-trade", name: "Fair Trade", tag_type: "pricing", color: "#22d3ee" },

  // --- Organization Tags ---
  { id: "tag_volunteer_needed", handle: "volunteer-needed", name: "Volunteer-needed", tag_type: "organization", color: "#ef4444" },
  { id: "tag_donation", handle: "donation", name: "Donation", tag_type: "organization", color: "#f43f5e" },
  { id: "tag_open", handle: "open", name: "Open", tag_type: "organization", color: "#22c55e" },
  { id: "tag_membership", handle: "membership", name: "Membership", tag_type: "organization", color: "#6366f1" },
  { id: "tag_workshops", handle: "workshops", name: "Workshops", tag_type: "organization", color: "#8b5cf6" },
  { id: "tag_produce_sharing", handle: "produce-sharing", name: "Produce-sharing", tag_type: "organization", color: "#84cc16" },
  { id: "tag_urban_farming", handle: "urban-farming", name: "Urban Farming", tag_type: "organization", color: "#22c55e" },
  { id: "tag_shared_kitchens", handle: "shared-kitchens", name: "Shared Kitchens", tag_type: "organization", color: "#f59e0b" },
  { id: "tag_equipment_access", handle: "equipment-access", name: "Equipment Access", tag_type: "organization", color: "#0ea5e9" },
  { id: "tag_booking_available", handle: "booking-available", name: "Booking Available", tag_type: "organization", color: "#10b981" },

  // --- Location Tags ---
  { id: "tag_city", handle: "city", name: "City", tag_type: "location", color: "#64748b" },
  { id: "tag_neighborhood", handle: "neighborhood", name: "Neighborhood", tag_type: "location", color: "#78716c" },
  { id: "tag_region", handle: "region", name: "Region", tag_type: "location", color: "#71717a" },
  { id: "tag_zip_code", handle: "zip-code", name: "Zip code", tag_type: "location", color: "#737373" },
  { id: "tag_distance_radius", handle: "distance-radius", name: "Distance radius", tag_type: "location", color: "#525252" },

  // --- Service Tags ---
  { id: "tag_on_demand", handle: "on-demand", name: "On-demand", tag_type: "service", color: "#f43f5e" },
  { id: "tag_scheduled", handle: "scheduled", name: "Scheduled", tag_type: "service", color: "#6366f1" },

  // --- Facility Tags ---
  { id: "tag_food", handle: "food", name: "Food", tag_type: "facility", color: "#f97316" },
  { id: "tag_clothing", handle: "clothing", name: "Clothing", tag_type: "facility", color: "#a855f7" },
  { id: "tag_housing", handle: "housing", name: "Housing", tag_type: "facility", color: "#0ea5e9" },
  { id: "tag_education", handle: "education", name: "Education", tag_type: "facility", color: "#8b5cf6" },

  // --- Condition Tags ---
  { id: "tag_new", handle: "new", name: "New", tag_type: "condition", color: "#22c55e" },
  { id: "tag_used", handle: "used", name: "Used", tag_type: "condition", color: "#f59e0b" },
  { id: "tag_refurbished", handle: "refurbished", name: "Refurbished", tag_type: "condition", color: "#3b82f6" },

  // --- Portion Tags ---
  { id: "tag_single", handle: "single", name: "Single", tag_type: "portion", color: "#94a3b8" },
  { id: "tag_family", handle: "family", name: "Family", tag_type: "portion", color: "#64748b" },
  { id: "tag_bulk", handle: "bulk", name: "Bulk", tag_type: "portion", color: "#475569" },

  // --- Additional Tags ---
  { id: "tag_recyclable", handle: "recyclable", name: "Recyclable", tag_type: "source", color: "#22d3ee" },
  { id: "tag_eco_friendly", handle: "eco-friendly", name: "Eco-Friendly", tag_type: "source", color: "#34d399" },
]

// ============================================================================
// ATTRIBUTES - Product/service attribute definitions
// ============================================================================
export const CMS_ATTRIBUTES = [
  // --- Common Product Attributes ---
  {
    id: "attr_price",
    handle: "price",
    name: "Price",
    description: "Product or service price",
    input_type: "number",
    display_type: "range_slider",
    unit: "$",
    validation: { min: 0 },
    is_filterable: true,
    is_required: true,
    display_order: 1,
  },
  {
    id: "attr_quantity_weight",
    handle: "quantity-weight",
    name: "Quantity / Weight",
    description: "Product quantity or weight",
    input_type: "text",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 2,
  },
  {
    id: "attr_quantity_volume",
    handle: "quantity-volume",
    name: "Quantity / Volume",
    description: "Product quantity or volume",
    input_type: "text",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 3,
  },
  {
    id: "attr_quantity_portions",
    handle: "quantity-portions",
    name: "Quantity / Portions",
    description: "Number of portions or servings",
    input_type: "number",
    display_type: "number_input",
    unit: "portions",
    validation: { min: 1 },
    is_filterable: true,
    is_required: false,
    display_order: 4,
  },
  {
    id: "attr_quantity_units",
    handle: "quantity-units",
    name: "Quantity / Units",
    description: "Number of units in package",
    input_type: "number",
    display_type: "number_input",
    unit: "units",
    validation: { min: 1 },
    is_filterable: true,
    is_required: false,
    display_order: 5,
  },

  // --- Freshness & Expiration Attributes ---
  {
    id: "attr_freshness",
    handle: "freshness",
    name: "Freshness",
    description: "Product freshness state",
    input_type: "select",
    display_type: "dropdown",
    unit: null,
    options: ["Fresh", "Frozen", "Canned", "Dried"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 6,
  },
  {
    id: "attr_expiration_date",
    handle: "expiration-date",
    name: "Expiration Date",
    description: "Product expiration or best-by date",
    input_type: "date",
    display_type: "date_picker",
    unit: null,
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 7,
  },

  // --- Delivery & Fulfillment Attributes ---
  {
    id: "attr_delivery_radius",
    handle: "delivery-radius",
    name: "Delivery Radius",
    description: "Maximum delivery distance",
    input_type: "number",
    display_type: "range_slider",
    unit: "miles",
    validation: { min: 0, max: 100 },
    is_filterable: true,
    is_required: false,
    display_order: 8,
  },
  {
    id: "attr_pickup_availability",
    handle: "pickup-availability",
    name: "Pickup Availability",
    description: "Whether pickup is available",
    input_type: "boolean",
    display_type: "checkbox",
    unit: null,
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 9,
  },
  {
    id: "attr_delivery_options",
    handle: "delivery-options",
    name: "Delivery / Pickup Options",
    description: "Available fulfillment options",
    input_type: "multiselect",
    display_type: "multiselect",
    unit: null,
    options: ["Delivery", "Pickup", "Shipping"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 10,
  },

  // --- Service Attributes ---
  {
    id: "attr_price_fee",
    handle: "price-fee",
    name: "Price / Fee",
    description: "Service fee or price",
    input_type: "number",
    display_type: "range_slider",
    unit: "$",
    validation: { min: 0 },
    is_filterable: true,
    is_required: false,
    display_order: 11,
  },
  {
    id: "attr_service_area",
    handle: "service-area",
    name: "Service Area / Radius",
    description: "Geographic service coverage",
    input_type: "text",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 12,
  },
  {
    id: "attr_scheduling",
    handle: "scheduling",
    name: "Scheduling",
    description: "Available days and hours",
    input_type: "json",
    display_type: "tags",
    unit: null,
    validation: null,
    is_filterable: false,
    is_required: false,
    display_order: 13,
  },

  // --- Organization Attributes ---
  {
    id: "attr_contact_info",
    handle: "contact-info",
    name: "Contact Info",
    description: "Organization contact information",
    input_type: "json",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: false,
    is_required: false,
    display_order: 14,
  },
  {
    id: "attr_hours_operation",
    handle: "hours-operation",
    name: "Hours of Operation",
    description: "Operating hours",
    input_type: "json",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: false,
    is_required: false,
    display_order: 15,
  },
  {
    id: "attr_volunteer_opportunities",
    handle: "volunteer-opportunities",
    name: "Volunteer Opportunities",
    description: "Available volunteer positions",
    input_type: "text",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 16,
  },
  {
    id: "attr_events",
    handle: "events",
    name: "Events",
    description: "Upcoming events and activities",
    input_type: "json",
    display_type: "tags",
    unit: null,
    validation: null,
    is_filterable: false,
    is_required: false,
    display_order: 17,
  },
  {
    id: "attr_participation_options",
    handle: "participation-options",
    name: "Participation Options",
    description: "Ways to participate",
    input_type: "multiselect",
    display_type: "multiselect",
    unit: null,
    options: ["Volunteer", "Donate", "Attend", "Membership"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 18,
  },

  // --- Community Garden Attributes ---
  {
    id: "attr_membership_requirements",
    handle: "membership-requirements",
    name: "Membership Requirements",
    description: "Requirements to join",
    input_type: "text",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: false,
    is_required: false,
    display_order: 19,
  },
  {
    id: "attr_access_type",
    handle: "access-type",
    name: "Access Type",
    description: "Type of access available",
    input_type: "select",
    display_type: "dropdown",
    unit: null,
    options: ["Public", "Private", "Limited"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 20,
  },
  {
    id: "attr_available_resources",
    handle: "available-resources",
    name: "Available Resources",
    description: "Resources available at the location",
    input_type: "multiselect",
    display_type: "multiselect",
    unit: null,
    options: ["Land Plots", "Tools", "Seeds", "Water", "Compost", "Storage"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 21,
  },
  {
    id: "attr_booking_options",
    handle: "booking-options",
    name: "Booking / Reservation Options",
    description: "How to book or reserve",
    input_type: "text",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: false,
    is_required: false,
    display_order: 22,
  },

  // --- Community Kitchen Attributes ---
  {
    id: "attr_kitchen_stations",
    handle: "kitchen-stations",
    name: "Kitchen Stations",
    description: "Number of kitchen stations available",
    input_type: "number",
    display_type: "number_input",
    unit: "stations",
    validation: { min: 1 },
    is_filterable: true,
    is_required: false,
    display_order: 23,
  },
  {
    id: "attr_appliances_available",
    handle: "appliances-available",
    name: "Appliances Available",
    description: "Kitchen appliances available for use",
    input_type: "multiselect",
    display_type: "multiselect",
    unit: null,
    options: ["Ovens", "Stoves", "Refrigerators", "Freezers", "Mixers", "Food Processors", "Dishwashers", "Prep Tables"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 24,
  },
  {
    id: "attr_booking_system",
    handle: "booking-system",
    name: "Booking System",
    description: "How to book the facility",
    input_type: "select",
    display_type: "dropdown",
    unit: null,
    options: ["Online", "Phone", "In-person", "Email"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 25,
  },
  {
    id: "attr_staffed",
    handle: "staffed",
    name: "Volunteer/Staffed",
    description: "Whether facility is staffed",
    input_type: "select",
    display_type: "dropdown",
    unit: null,
    options: ["Staffed", "Volunteer", "Self-service"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 26,
  },

  // --- Equipment Attributes ---
  {
    id: "attr_size_weight",
    handle: "size-weight",
    name: "Size / Weight",
    description: "Equipment dimensions or weight",
    input_type: "text",
    display_type: "text_input",
    unit: null,
    validation: null,
    is_filterable: false,
    is_required: false,
    display_order: 27,
  },
  {
    id: "attr_shipping_pickup",
    handle: "shipping-pickup",
    name: "Shipping / Pickup",
    description: "Fulfillment method for equipment",
    input_type: "multiselect",
    display_type: "multiselect",
    unit: null,
    options: ["Shipping", "Pickup", "Local Delivery"],
    validation: null,
    is_filterable: true,
    is_required: false,
    display_order: 28,
  },

  // --- Prepared Food Attributes ---
  {
    id: "attr_price_per_serving",
    handle: "price-per-serving",
    name: "Price per serving/package",
    description: "Price per individual serving or package",
    input_type: "number",
    display_type: "range_slider",
    unit: "$",
    validation: { min: 0 },
    is_filterable: true,
    is_required: false,
    display_order: 29,
  },
]

// ============================================================================
// CATEGORY-TAG MAPPINGS - Which tags apply to each category
// ============================================================================
export const CMS_CATEGORY_TAG_MAPPINGS = [
  // --- Food & Produce: Fruits ---
  { category_id: "cat_fruits", tag_id: "tag_organic" },
  { category_id: "cat_fruits", tag_id: "tag_vegan" },
  { category_id: "cat_fruits", tag_id: "tag_in_stock" },
  { category_id: "cat_fruits", tag_id: "tag_seasonal" },
  { category_id: "cat_fruits", tag_id: "tag_pre_order" },
  { category_id: "cat_fruits", tag_id: "tag_farm" },
  { category_id: "cat_fruits", tag_id: "tag_artisan" },
  { category_id: "cat_fruits", tag_id: "tag_nonprofit" },
  { category_id: "cat_fruits", tag_id: "tag_delivery" },
  { category_id: "cat_fruits", tag_id: "tag_pickup" },
  { category_id: "cat_fruits", tag_id: "tag_local_only" },
  { category_id: "cat_fruits", tag_id: "tag_bulk_sale" },
  { category_id: "cat_fruits", tag_id: "tag_fair_trade" },

  // --- Food & Produce: Vegetables ---
  { category_id: "cat_vegetables", tag_id: "tag_organic" },
  { category_id: "cat_vegetables", tag_id: "tag_vegan" },
  { category_id: "cat_vegetables", tag_id: "tag_in_stock" },
  { category_id: "cat_vegetables", tag_id: "tag_seasonal" },
  { category_id: "cat_vegetables", tag_id: "tag_pre_order" },
  { category_id: "cat_vegetables", tag_id: "tag_farm" },
  { category_id: "cat_vegetables", tag_id: "tag_artisan" },
  { category_id: "cat_vegetables", tag_id: "tag_nonprofit" },
  { category_id: "cat_vegetables", tag_id: "tag_delivery" },
  { category_id: "cat_vegetables", tag_id: "tag_pickup" },
  { category_id: "cat_vegetables", tag_id: "tag_local_only" },
  { category_id: "cat_vegetables", tag_id: "tag_bulk_sale" },
  { category_id: "cat_vegetables", tag_id: "tag_fair_trade" },

  // --- Food & Produce: Grains & Legumes ---
  { category_id: "cat_grains_legumes", tag_id: "tag_organic" },
  { category_id: "cat_grains_legumes", tag_id: "tag_vegan" },
  { category_id: "cat_grains_legumes", tag_id: "tag_gluten_free" },
  { category_id: "cat_grains_legumes", tag_id: "tag_in_stock" },
  { category_id: "cat_grains_legumes", tag_id: "tag_pre_order" },
  { category_id: "cat_grains_legumes", tag_id: "tag_farm" },
  { category_id: "cat_grains_legumes", tag_id: "tag_artisan" },
  { category_id: "cat_grains_legumes", tag_id: "tag_nonprofit" },
  { category_id: "cat_grains_legumes", tag_id: "tag_bulk_sale" },
  { category_id: "cat_grains_legumes", tag_id: "tag_delivery" },
  { category_id: "cat_grains_legumes", tag_id: "tag_pickup" },

  // --- Food & Produce: Meat & Seafood ---
  { category_id: "cat_meat_seafood", tag_id: "tag_in_stock" },
  { category_id: "cat_meat_seafood", tag_id: "tag_pre_order" },
  { category_id: "cat_meat_seafood", tag_id: "tag_local_only" },
  { category_id: "cat_meat_seafood", tag_id: "tag_farm" },
  { category_id: "cat_meat_seafood", tag_id: "tag_nonprofit" },
  { category_id: "cat_meat_seafood", tag_id: "tag_delivery" },
  { category_id: "cat_meat_seafood", tag_id: "tag_pickup" },

  // --- Food & Produce: Dairy & Eggs ---
  { category_id: "cat_dairy_eggs", tag_id: "tag_organic" },
  { category_id: "cat_dairy_eggs", tag_id: "tag_in_stock" },
  { category_id: "cat_dairy_eggs", tag_id: "tag_pre_order" },
  { category_id: "cat_dairy_eggs", tag_id: "tag_farm" },
  { category_id: "cat_dairy_eggs", tag_id: "tag_nonprofit" },
  { category_id: "cat_dairy_eggs", tag_id: "tag_delivery" },
  { category_id: "cat_dairy_eggs", tag_id: "tag_pickup" },

  // --- Food & Produce: Beverages ---
  { category_id: "cat_beverages_produce", tag_id: "tag_organic" },
  { category_id: "cat_beverages_produce", tag_id: "tag_vegan" },
  { category_id: "cat_beverages_produce", tag_id: "tag_in_stock" },
  { category_id: "cat_beverages_produce", tag_id: "tag_seasonal" },
  { category_id: "cat_beverages_produce", tag_id: "tag_farm" },
  { category_id: "cat_beverages_produce", tag_id: "tag_artisan" },
  { category_id: "cat_beverages_produce", tag_id: "tag_nonprofit" },
  { category_id: "cat_beverages_produce", tag_id: "tag_delivery" },
  { category_id: "cat_beverages_produce", tag_id: "tag_pickup" },
  { category_id: "cat_beverages_produce", tag_id: "tag_bulk_sale" },
  { category_id: "cat_beverages_produce", tag_id: "tag_fair_trade" },

  // --- Prepared Foods: Breakfast ---
  { category_id: "cat_breakfast", tag_id: "tag_vegan" },
  { category_id: "cat_breakfast", tag_id: "tag_gluten_free" },
  { category_id: "cat_breakfast", tag_id: "tag_keto" },
  { category_id: "cat_breakfast", tag_id: "tag_low_sugar" },
  { category_id: "cat_breakfast", tag_id: "tag_ready_to_eat" },
  { category_id: "cat_breakfast", tag_id: "tag_pre_order" },
  { category_id: "cat_breakfast", tag_id: "tag_seasonal" },
  { category_id: "cat_breakfast", tag_id: "tag_single" },
  { category_id: "cat_breakfast", tag_id: "tag_family" },
  { category_id: "cat_breakfast", tag_id: "tag_bulk" },
  { category_id: "cat_breakfast", tag_id: "tag_delivery" },
  { category_id: "cat_breakfast", tag_id: "tag_pickup" },
  { category_id: "cat_breakfast", tag_id: "tag_locally_made" },
  { category_id: "cat_breakfast", tag_id: "tag_artisanal" },

  // --- Prepared Foods: Lunch & Dinner ---
  { category_id: "cat_lunch_dinner", tag_id: "tag_vegan" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_gluten_free" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_keto" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_low_sugar" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_ready_to_eat" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_pre_order" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_seasonal" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_single" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_family" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_bulk" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_delivery" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_pickup" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_locally_made" },
  { category_id: "cat_lunch_dinner", tag_id: "tag_artisanal" },

  // --- Prepared Foods: Snacks ---
  { category_id: "cat_snacks", tag_id: "tag_vegan" },
  { category_id: "cat_snacks", tag_id: "tag_gluten_free" },
  { category_id: "cat_snacks", tag_id: "tag_keto" },
  { category_id: "cat_snacks", tag_id: "tag_low_sugar" },
  { category_id: "cat_snacks", tag_id: "tag_ready_to_eat" },
  { category_id: "cat_snacks", tag_id: "tag_pre_order" },
  { category_id: "cat_snacks", tag_id: "tag_seasonal" },
  { category_id: "cat_snacks", tag_id: "tag_single" },
  { category_id: "cat_snacks", tag_id: "tag_family" },
  { category_id: "cat_snacks", tag_id: "tag_bulk" },
  { category_id: "cat_snacks", tag_id: "tag_delivery" },
  { category_id: "cat_snacks", tag_id: "tag_pickup" },
  { category_id: "cat_snacks", tag_id: "tag_locally_made" },
  { category_id: "cat_snacks", tag_id: "tag_artisanal" },

  // --- Prepared Foods: Desserts ---
  { category_id: "cat_desserts", tag_id: "tag_vegan" },
  { category_id: "cat_desserts", tag_id: "tag_gluten_free" },
  { category_id: "cat_desserts", tag_id: "tag_keto" },
  { category_id: "cat_desserts", tag_id: "tag_low_sugar" },
  { category_id: "cat_desserts", tag_id: "tag_ready_to_eat" },
  { category_id: "cat_desserts", tag_id: "tag_pre_order" },
  { category_id: "cat_desserts", tag_id: "tag_seasonal" },
  { category_id: "cat_desserts", tag_id: "tag_single" },
  { category_id: "cat_desserts", tag_id: "tag_family" },
  { category_id: "cat_desserts", tag_id: "tag_bulk" },
  { category_id: "cat_desserts", tag_id: "tag_delivery" },
  { category_id: "cat_desserts", tag_id: "tag_pickup" },
  { category_id: "cat_desserts", tag_id: "tag_locally_made" },
  { category_id: "cat_desserts", tag_id: "tag_artisanal" },

  // --- Prepared Foods: Beverages ---
  { category_id: "cat_beverages_prepared", tag_id: "tag_vegan" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_gluten_free" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_keto" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_low_sugar" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_ready_to_eat" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_pre_order" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_seasonal" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_single" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_family" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_bulk" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_delivery" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_pickup" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_locally_made" },
  { category_id: "cat_beverages_prepared", tag_id: "tag_artisanal" },

  // --- Supplies & Goods: Household Items ---
  { category_id: "cat_household_items", tag_id: "tag_artisan" },
  { category_id: "cat_household_items", tag_id: "tag_maker" },
  { category_id: "cat_household_items", tag_id: "tag_nonprofit" },
  { category_id: "cat_household_items", tag_id: "tag_in_stock" },
  { category_id: "cat_household_items", tag_id: "tag_pre_order" },
  { category_id: "cat_household_items", tag_id: "tag_recyclable" },
  { category_id: "cat_household_items", tag_id: "tag_bulk" },
  { category_id: "cat_household_items", tag_id: "tag_eco_friendly" },
  { category_id: "cat_household_items", tag_id: "tag_delivery" },
  { category_id: "cat_household_items", tag_id: "tag_pickup" },

  // --- Supplies & Goods: Personal Care ---
  { category_id: "cat_personal_care", tag_id: "tag_artisan" },
  { category_id: "cat_personal_care", tag_id: "tag_maker" },
  { category_id: "cat_personal_care", tag_id: "tag_nonprofit" },
  { category_id: "cat_personal_care", tag_id: "tag_in_stock" },
  { category_id: "cat_personal_care", tag_id: "tag_pre_order" },
  { category_id: "cat_personal_care", tag_id: "tag_recyclable" },
  { category_id: "cat_personal_care", tag_id: "tag_bulk" },
  { category_id: "cat_personal_care", tag_id: "tag_eco_friendly" },
  { category_id: "cat_personal_care", tag_id: "tag_delivery" },
  { category_id: "cat_personal_care", tag_id: "tag_pickup" },

  // --- Supplies & Goods: Cleaning Supplies ---
  { category_id: "cat_cleaning_supplies", tag_id: "tag_artisan" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_maker" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_nonprofit" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_in_stock" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_pre_order" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_recyclable" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_bulk" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_eco_friendly" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_delivery" },
  { category_id: "cat_cleaning_supplies", tag_id: "tag_pickup" },

  // --- Supplies & Goods: Pantry Staples ---
  { category_id: "cat_pantry_staples", tag_id: "tag_artisan" },
  { category_id: "cat_pantry_staples", tag_id: "tag_maker" },
  { category_id: "cat_pantry_staples", tag_id: "tag_nonprofit" },
  { category_id: "cat_pantry_staples", tag_id: "tag_in_stock" },
  { category_id: "cat_pantry_staples", tag_id: "tag_pre_order" },
  { category_id: "cat_pantry_staples", tag_id: "tag_recyclable" },
  { category_id: "cat_pantry_staples", tag_id: "tag_bulk" },
  { category_id: "cat_pantry_staples", tag_id: "tag_eco_friendly" },
  { category_id: "cat_pantry_staples", tag_id: "tag_delivery" },
  { category_id: "cat_pantry_staples", tag_id: "tag_pickup" },

  // --- Services & Delivery: Local Delivery ---
  { category_id: "cat_local_delivery", tag_id: "tag_delivery" },
  { category_id: "cat_local_delivery", tag_id: "tag_on_demand" },
  { category_id: "cat_local_delivery", tag_id: "tag_scheduled" },
  { category_id: "cat_local_delivery", tag_id: "tag_city" },
  { category_id: "cat_local_delivery", tag_id: "tag_neighborhood" },
  { category_id: "cat_local_delivery", tag_id: "tag_distance_radius" },

  // --- Services & Delivery: Catering & Meal Prep ---
  { category_id: "cat_catering_meal_prep", tag_id: "tag_delivery" },
  { category_id: "cat_catering_meal_prep", tag_id: "tag_on_demand" },
  { category_id: "cat_catering_meal_prep", tag_id: "tag_scheduled" },
  { category_id: "cat_catering_meal_prep", tag_id: "tag_city" },
  { category_id: "cat_catering_meal_prep", tag_id: "tag_neighborhood" },
  { category_id: "cat_catering_meal_prep", tag_id: "tag_distance_radius" },

  // --- Services & Delivery: Transport & Logistics ---
  { category_id: "cat_transport_logistics", tag_id: "tag_delivery" },
  { category_id: "cat_transport_logistics", tag_id: "tag_on_demand" },
  { category_id: "cat_transport_logistics", tag_id: "tag_scheduled" },
  { category_id: "cat_transport_logistics", tag_id: "tag_city" },
  { category_id: "cat_transport_logistics", tag_id: "tag_neighborhood" },
  { category_id: "cat_transport_logistics", tag_id: "tag_distance_radius" },

  // --- Organizations: Food Banks ---
  { category_id: "cat_food_banks", tag_id: "tag_food" },
  { category_id: "cat_food_banks", tag_id: "tag_open" },
  { category_id: "cat_food_banks", tag_id: "tag_volunteer_needed" },
  { category_id: "cat_food_banks", tag_id: "tag_donation" },
  { category_id: "cat_food_banks", tag_id: "tag_city" },
  { category_id: "cat_food_banks", tag_id: "tag_zip_code" },
  { category_id: "cat_food_banks", tag_id: "tag_region" },

  // --- Organizations: Mutual Aid Groups ---
  { category_id: "cat_mutual_aid", tag_id: "tag_food" },
  { category_id: "cat_mutual_aid", tag_id: "tag_clothing" },
  { category_id: "cat_mutual_aid", tag_id: "tag_housing" },
  { category_id: "cat_mutual_aid", tag_id: "tag_education" },
  { category_id: "cat_mutual_aid", tag_id: "tag_open" },
  { category_id: "cat_mutual_aid", tag_id: "tag_volunteer_needed" },
  { category_id: "cat_mutual_aid", tag_id: "tag_donation" },
  { category_id: "cat_mutual_aid", tag_id: "tag_city" },
  { category_id: "cat_mutual_aid", tag_id: "tag_zip_code" },
  { category_id: "cat_mutual_aid", tag_id: "tag_region" },

  // --- Organizations: Community Programs ---
  { category_id: "cat_community_programs", tag_id: "tag_food" },
  { category_id: "cat_community_programs", tag_id: "tag_education" },
  { category_id: "cat_community_programs", tag_id: "tag_workshops" },
  { category_id: "cat_community_programs", tag_id: "tag_open" },
  { category_id: "cat_community_programs", tag_id: "tag_volunteer_needed" },
  { category_id: "cat_community_programs", tag_id: "tag_donation" },
  { category_id: "cat_community_programs", tag_id: "tag_city" },
  { category_id: "cat_community_programs", tag_id: "tag_neighborhood" },
  { category_id: "cat_community_programs", tag_id: "tag_region" },

  // --- Organizations: Community Gardens ---
  { category_id: "cat_community_gardens", tag_id: "tag_urban_farming" },
  { category_id: "cat_community_gardens", tag_id: "tag_volunteer_needed" },
  { category_id: "cat_community_gardens", tag_id: "tag_open" },
  { category_id: "cat_community_gardens", tag_id: "tag_membership" },
  { category_id: "cat_community_gardens", tag_id: "tag_workshops" },
  { category_id: "cat_community_gardens", tag_id: "tag_produce_sharing" },
  { category_id: "cat_community_gardens", tag_id: "tag_city" },
  { category_id: "cat_community_gardens", tag_id: "tag_neighborhood" },
  { category_id: "cat_community_gardens", tag_id: "tag_region" },

  // --- Organizations: Community Commercial Kitchens ---
  { category_id: "cat_community_kitchens", tag_id: "tag_shared_kitchens" },
  { category_id: "cat_community_kitchens", tag_id: "tag_equipment_access" },
  { category_id: "cat_community_kitchens", tag_id: "tag_workshops" },
  { category_id: "cat_community_kitchens", tag_id: "tag_open" },
  { category_id: "cat_community_kitchens", tag_id: "tag_membership" },
  { category_id: "cat_community_kitchens", tag_id: "tag_booking_available" },
  { category_id: "cat_community_kitchens", tag_id: "tag_city" },
  { category_id: "cat_community_kitchens", tag_id: "tag_neighborhood" },
  { category_id: "cat_community_kitchens", tag_id: "tag_region" },

  // --- Equipment & Tools: Kitchen Equipment ---
  { category_id: "cat_kitchen_equipment", tag_id: "tag_farm" },
  { category_id: "cat_kitchen_equipment", tag_id: "tag_maker" },
  { category_id: "cat_kitchen_equipment", tag_id: "tag_artisan" },
  { category_id: "cat_kitchen_equipment", tag_id: "tag_new" },
  { category_id: "cat_kitchen_equipment", tag_id: "tag_used" },
  { category_id: "cat_kitchen_equipment", tag_id: "tag_refurbished" },
  { category_id: "cat_kitchen_equipment", tag_id: "tag_in_stock" },
  { category_id: "cat_kitchen_equipment", tag_id: "tag_pre_order" },

  // --- Equipment & Tools: Gardening Tools ---
  { category_id: "cat_gardening_tools", tag_id: "tag_farm" },
  { category_id: "cat_gardening_tools", tag_id: "tag_maker" },
  { category_id: "cat_gardening_tools", tag_id: "tag_artisan" },
  { category_id: "cat_gardening_tools", tag_id: "tag_new" },
  { category_id: "cat_gardening_tools", tag_id: "tag_used" },
  { category_id: "cat_gardening_tools", tag_id: "tag_refurbished" },
  { category_id: "cat_gardening_tools", tag_id: "tag_in_stock" },
  { category_id: "cat_gardening_tools", tag_id: "tag_pre_order" },

  // --- Equipment & Tools: Small Machinery ---
  { category_id: "cat_small_machinery", tag_id: "tag_farm" },
  { category_id: "cat_small_machinery", tag_id: "tag_maker" },
  { category_id: "cat_small_machinery", tag_id: "tag_artisan" },
  { category_id: "cat_small_machinery", tag_id: "tag_new" },
  { category_id: "cat_small_machinery", tag_id: "tag_used" },
  { category_id: "cat_small_machinery", tag_id: "tag_refurbished" },
  { category_id: "cat_small_machinery", tag_id: "tag_in_stock" },
  { category_id: "cat_small_machinery", tag_id: "tag_pre_order" },
]

// ============================================================================
// CATEGORY-ATTRIBUTE MAPPINGS - Which attributes apply to each category
// ============================================================================
export const CMS_CATEGORY_ATTRIBUTE_MAPPINGS = [
  // --- Food & Produce Categories: Common Attributes ---
  // Fruits
  { category_id: "cat_fruits", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_fruits", attribute_id: "attr_quantity_weight" },
  { category_id: "cat_fruits", attribute_id: "attr_freshness" },
  { category_id: "cat_fruits", attribute_id: "attr_expiration_date" },
  { category_id: "cat_fruits", attribute_id: "attr_delivery_radius" },
  { category_id: "cat_fruits", attribute_id: "attr_pickup_availability" },

  // Vegetables
  { category_id: "cat_vegetables", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_vegetables", attribute_id: "attr_quantity_weight" },
  { category_id: "cat_vegetables", attribute_id: "attr_freshness" },
  { category_id: "cat_vegetables", attribute_id: "attr_expiration_date" },
  { category_id: "cat_vegetables", attribute_id: "attr_delivery_radius" },
  { category_id: "cat_vegetables", attribute_id: "attr_pickup_availability" },

  // Grains & Legumes
  { category_id: "cat_grains_legumes", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_grains_legumes", attribute_id: "attr_quantity_weight" },
  { category_id: "cat_grains_legumes", attribute_id: "attr_expiration_date" },
  { category_id: "cat_grains_legumes", attribute_id: "attr_delivery_radius" },
  { category_id: "cat_grains_legumes", attribute_id: "attr_pickup_availability" },

  // Meat & Seafood
  { category_id: "cat_meat_seafood", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_meat_seafood", attribute_id: "attr_quantity_weight" },
  { category_id: "cat_meat_seafood", attribute_id: "attr_freshness" },
  { category_id: "cat_meat_seafood", attribute_id: "attr_expiration_date" },
  { category_id: "cat_meat_seafood", attribute_id: "attr_delivery_radius" },
  { category_id: "cat_meat_seafood", attribute_id: "attr_pickup_availability" },

  // Dairy & Eggs
  { category_id: "cat_dairy_eggs", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_dairy_eggs", attribute_id: "attr_quantity_weight" },
  { category_id: "cat_dairy_eggs", attribute_id: "attr_freshness" },
  { category_id: "cat_dairy_eggs", attribute_id: "attr_expiration_date" },
  { category_id: "cat_dairy_eggs", attribute_id: "attr_delivery_radius" },
  { category_id: "cat_dairy_eggs", attribute_id: "attr_pickup_availability" },

  // Beverages (Produce)
  { category_id: "cat_beverages_produce", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_beverages_produce", attribute_id: "attr_quantity_volume" },
  { category_id: "cat_beverages_produce", attribute_id: "attr_expiration_date" },
  { category_id: "cat_beverages_produce", attribute_id: "attr_delivery_radius" },
  { category_id: "cat_beverages_produce", attribute_id: "attr_pickup_availability" },

  // --- Prepared Foods Categories ---
  // Breakfast
  { category_id: "cat_breakfast", attribute_id: "attr_price_per_serving", is_required: true },
  { category_id: "cat_breakfast", attribute_id: "attr_quantity_portions" },
  { category_id: "cat_breakfast", attribute_id: "attr_freshness" },
  { category_id: "cat_breakfast", attribute_id: "attr_delivery_options" },

  // Lunch & Dinner
  { category_id: "cat_lunch_dinner", attribute_id: "attr_price_per_serving", is_required: true },
  { category_id: "cat_lunch_dinner", attribute_id: "attr_quantity_portions" },
  { category_id: "cat_lunch_dinner", attribute_id: "attr_freshness" },
  { category_id: "cat_lunch_dinner", attribute_id: "attr_delivery_options" },

  // Snacks
  { category_id: "cat_snacks", attribute_id: "attr_price_per_serving", is_required: true },
  { category_id: "cat_snacks", attribute_id: "attr_quantity_portions" },
  { category_id: "cat_snacks", attribute_id: "attr_freshness" },
  { category_id: "cat_snacks", attribute_id: "attr_delivery_options" },

  // Desserts
  { category_id: "cat_desserts", attribute_id: "attr_price_per_serving", is_required: true },
  { category_id: "cat_desserts", attribute_id: "attr_quantity_portions" },
  { category_id: "cat_desserts", attribute_id: "attr_freshness" },
  { category_id: "cat_desserts", attribute_id: "attr_delivery_options" },

  // Beverages (Prepared)
  { category_id: "cat_beverages_prepared", attribute_id: "attr_price_per_serving", is_required: true },
  { category_id: "cat_beverages_prepared", attribute_id: "attr_quantity_portions" },
  { category_id: "cat_beverages_prepared", attribute_id: "attr_freshness" },
  { category_id: "cat_beverages_prepared", attribute_id: "attr_delivery_options" },

  // --- Supplies & Goods Categories ---
  // Household Items
  { category_id: "cat_household_items", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_household_items", attribute_id: "attr_quantity_units" },

  // Personal Care
  { category_id: "cat_personal_care", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_personal_care", attribute_id: "attr_quantity_units" },

  // Cleaning Supplies
  { category_id: "cat_cleaning_supplies", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_cleaning_supplies", attribute_id: "attr_quantity_units" },

  // Pantry Staples
  { category_id: "cat_pantry_staples", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_pantry_staples", attribute_id: "attr_quantity_units" },

  // --- Services & Delivery Categories ---
  // Local Delivery
  { category_id: "cat_local_delivery", attribute_id: "attr_price_fee", is_required: true },
  { category_id: "cat_local_delivery", attribute_id: "attr_service_area" },
  { category_id: "cat_local_delivery", attribute_id: "attr_scheduling" },

  // Catering & Meal Prep
  { category_id: "cat_catering_meal_prep", attribute_id: "attr_price_fee", is_required: true },
  { category_id: "cat_catering_meal_prep", attribute_id: "attr_service_area" },
  { category_id: "cat_catering_meal_prep", attribute_id: "attr_scheduling" },

  // Transport & Logistics
  { category_id: "cat_transport_logistics", attribute_id: "attr_price_fee", is_required: true },
  { category_id: "cat_transport_logistics", attribute_id: "attr_service_area" },
  { category_id: "cat_transport_logistics", attribute_id: "attr_scheduling" },

  // --- Organizations Categories ---
  // Food Banks
  { category_id: "cat_food_banks", attribute_id: "attr_contact_info" },
  { category_id: "cat_food_banks", attribute_id: "attr_hours_operation" },
  { category_id: "cat_food_banks", attribute_id: "attr_volunteer_opportunities" },

  // Mutual Aid Groups
  { category_id: "cat_mutual_aid", attribute_id: "attr_contact_info" },
  { category_id: "cat_mutual_aid", attribute_id: "attr_hours_operation" },
  { category_id: "cat_mutual_aid", attribute_id: "attr_volunteer_opportunities" },

  // Community Programs
  { category_id: "cat_community_programs", attribute_id: "attr_contact_info" },
  { category_id: "cat_community_programs", attribute_id: "attr_hours_operation" },
  { category_id: "cat_community_programs", attribute_id: "attr_events" },
  { category_id: "cat_community_programs", attribute_id: "attr_participation_options" },

  // Community Gardens
  { category_id: "cat_community_gardens", attribute_id: "attr_contact_info" },
  { category_id: "cat_community_gardens", attribute_id: "attr_hours_operation" },
  { category_id: "cat_community_gardens", attribute_id: "attr_volunteer_opportunities" },
  { category_id: "cat_community_gardens", attribute_id: "attr_membership_requirements" },
  { category_id: "cat_community_gardens", attribute_id: "attr_access_type" },
  { category_id: "cat_community_gardens", attribute_id: "attr_available_resources" },
  { category_id: "cat_community_gardens", attribute_id: "attr_booking_options" },

  // Community Commercial Kitchens
  { category_id: "cat_community_kitchens", attribute_id: "attr_contact_info" },
  { category_id: "cat_community_kitchens", attribute_id: "attr_hours_operation" },
  { category_id: "cat_community_kitchens", attribute_id: "attr_kitchen_stations" },
  { category_id: "cat_community_kitchens", attribute_id: "attr_appliances_available" },
  { category_id: "cat_community_kitchens", attribute_id: "attr_booking_system" },
  { category_id: "cat_community_kitchens", attribute_id: "attr_staffed" },
  { category_id: "cat_community_kitchens", attribute_id: "attr_membership_requirements" },
  { category_id: "cat_community_kitchens", attribute_id: "attr_access_type" },

  // --- Equipment & Tools Categories ---
  // Kitchen Equipment
  { category_id: "cat_kitchen_equipment", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_kitchen_equipment", attribute_id: "attr_quantity_units" },
  { category_id: "cat_kitchen_equipment", attribute_id: "attr_size_weight" },
  { category_id: "cat_kitchen_equipment", attribute_id: "attr_shipping_pickup" },

  // Gardening Tools
  { category_id: "cat_gardening_tools", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_gardening_tools", attribute_id: "attr_quantity_units" },
  { category_id: "cat_gardening_tools", attribute_id: "attr_size_weight" },
  { category_id: "cat_gardening_tools", attribute_id: "attr_shipping_pickup" },

  // Small Machinery
  { category_id: "cat_small_machinery", attribute_id: "attr_price", is_required: true },
  { category_id: "cat_small_machinery", attribute_id: "attr_quantity_units" },
  { category_id: "cat_small_machinery", attribute_id: "attr_size_weight" },
  { category_id: "cat_small_machinery", attribute_id: "attr_shipping_pickup" },
]
